// frontend-vue/src/components/pages/SearchPage.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { fetchSkills, deleteSkill } from '../../api'
import type { Skill } from '../../types'

const query = ref('')
const skills = ref<Skill[]>([])

async function loadSkills() {
  try {
    skills.value = await fetchSkills(query.value || undefined)
  } catch {
    alert('Failed to load skills. Please try again.')
  }
}

onMounted(loadSkills)
watch(query, loadSkills)

async function handleDelete(id: string) {
  if (!window.confirm('Delete this skill?')) return
  try {
    await deleteSkill(id)
    skills.value = skills.value.filter(s => s.id !== id)
  } catch {
    alert('Failed to delete skill. Please try again.')
  }
}
</script>

<template>
  <main class="max-w-2xl mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold text-gray-900 mb-6">Skill Registry</h1>
    <input
      v-model="query"
      placeholder="Search skills..."
      class="w-full border border-gray-300 rounded-lg px-4 py-2 mb-6 focus:outline-none focus:ring-2 focus:ring-indigo-400"
    />
    <ul class="space-y-4">
      <li
        v-for="skill in skills"
        :key="skill.id"
        class="bg-white rounded-lg border border-gray-200 p-4 shadow-sm hover:shadow-md transition-shadow"
      >
        <RouterLink
          :to="`/skills/${skill.id}`"
          class="text-lg font-semibold text-indigo-600 hover:text-indigo-800"
        >
          {{ skill.name }}
        </RouterLink>
        <p class="text-gray-600 mt-1 text-sm">{{ skill.description }}</p>
        <button
          @click="handleDelete(skill.id)"
          class="mt-2 text-sm text-red-500 hover:text-red-700 transition-colors"
        >
          Delete
        </button>
      </li>
    </ul>
    <p v-if="skills.length === 0" class="text-gray-400 text-center mt-8">No skills found.</p>
  </main>
</template>

// frontend/src/pages/SearchPage.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { fetchSkills, deleteSkill } from '../api';
import type { Skill } from '../api';

export default function SearchPage() {
  const [query, setQuery] = useState('');
  const [skills, setSkills] = useState<Skill[]>([]);

  useEffect(() => {
    fetchSkills(query || undefined).then(setSkills);
  }, [query]);

  async function handleDelete(id: string) {
    if (!window.confirm('Delete this skill?')) return;
    try {
      await deleteSkill(id);
      setSkills((prev) => prev.filter((s) => s.id !== id));
    } catch {
      alert('Failed to delete skill. Please try again.');
    }
  }

  return (
    <main style={{ padding: '1rem' }}>
      <h1>Skill Registry</h1>
      <input
        placeholder="Search skills..."
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        style={{ width: '100%', padding: '0.5rem', marginBottom: '1rem' }}
      />
      <ul style={{ listStyle: 'none', padding: 0 }}>
        {skills.map((skill) => (
          <li key={skill.id} style={{ marginBottom: '1rem', borderBottom: '1px solid #eee', paddingBottom: '0.5rem' }}>
            <Link to={`/skills/${skill.id}`}><strong>{skill.name}</strong></Link>
            <p style={{ margin: '0.25rem 0 0' }}>{skill.description}</p>
            <button onClick={() => handleDelete(skill.id)} style={{ marginTop: '0.25rem' }}>
              Delete
            </button>
          </li>
        ))}
      </ul>
    </main>
  );
}
